// Linux (systemd --user) keepalive layer for the Pocket Agent daemon.
//
// Model A without a tray: the CLI calls `cxx enable/disable/status/…` for one-shot
// JSON actions, while the daemon itself is owned by a systemd user unit and survives
// terminal exit. Mirrors mac-agent.mjs (launchd) and win-agent.mjs (Task Scheduler).
//
// SEA binary: the unit points at process.execPath so no separate node is required.
// Dev mode: ExecStart = node main.mjs start.
import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { homedir, platform } from "node:os";
import { basename, dirname, join, resolve } from "node:path";
import process from "node:process";
import { spawnSync } from "node:child_process";

import { defaultConfigPath } from "./config.mjs";

export const UNIT_NAME = "cxx-remote.service";
export const UNIT_DESCRIPTION = "Pocket Agent remote daemon";

// How to invoke this daemon's `start` under systemd.
//   SEA binary (cxx / cxx-daemon):  [<binary>, "start"]
//   dev (node main.mjs):            [<node>, <main.mjs>, "start"]
// Paths are absolute: systemd's default WorkingDirectory is /, so a relative
// main.mjs from `node daemon/src/main.mjs enable` would fail under the unit.
function daemonProgramArguments(configPath) {
  const exec = resolve(process.execPath);
  const base = basename(exec).toLowerCase();
  const isNode = base === "node" || base === "node.exe";
  const script = process.argv[1] ? resolve(process.argv[1]) : null;
  const args = isNode && script ? [exec, script, "start"] : [exec, "start"];
  if (configPath && configPath !== defaultConfigPath()) args.push("--config", resolve(configPath));
  return args;
}

// systemd unit files: quote args that contain whitespace or shell-ish characters.
export function quoteSystemdArg(s) {
  const str = String(s);
  if (!/[\s"\\$`]/.test(str)) return str;
  return `"${str.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

export function buildExecStart(programArguments) {
  return programArguments.map(quoteSystemdArg).join(" ");
}

// Generous PATH so a user unit can find codex/claude even though systemd hands a
// minimal environment. resolveCodexCommand() also probes absolute locations.
export function systemdPath(home = homedir()) {
  return [
    join(home, ".local", "bin"),
    join(home, ".codex", "bin"),
    join(home, ".npm-global", "bin"),
    join(home, "bin"),
    "/usr/local/bin",
    "/usr/bin",
    "/bin",
    "/usr/sbin",
    "/sbin",
  ].join(":");
}

export function buildUnitFile({ programArguments, logPath, pathEnv, description = UNIT_DESCRIPTION }) {
  const execStart = buildExecStart(programArguments);
  const pathLine = pathEnv || systemdPath();
  return `# Generated by Pocket Agent — do not edit by hand; re-run \`cxx enable\` after moves/upgrades.
[Unit]
Description=${description}
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${execStart}
Restart=always
RestartSec=3
Environment=PATH=${pathLine}
StandardOutput=append:${logPath}
StandardError=append:${logPath}

[Install]
WantedBy=default.target
`;
}

function defaultRunSystemctl(args) {
  return spawnSync("systemctl", ["--user", ...args], { encoding: "utf8" });
}

function defaultHasSystemctl() {
  const res = spawnSync("systemctl", ["--version"], { encoding: "utf8" });
  return res.status === 0;
}

// Linger keeps user units alive after the last session (SSH) ends.
// Returns true / false / null (unknown / unavailable).
function defaultReadLinger(user) {
  const res = spawnSync("loginctl", ["show-user", user, "-p", "Linger", "--value"], {
    encoding: "utf8",
  });
  if (res.status !== 0) return null;
  const v = String(res.stdout || "").trim().toLowerCase();
  if (v === "yes") return true;
  if (v === "no") return false;
  return null;
}

// deps: configPath, homeDir, unitDir, runSystemctl, hasSystemctl, readLinger, user, log
export function makeDeps(overrides = {}) {
  const home = overrides.homeDir || homedir();
  return {
    configPath: overrides.configPath || defaultConfigPath(),
    homeDir: home,
    platform: overrides.platform || platform(),
    unitDir: overrides.unitDir || join(home, ".config", "systemd", "user"),
    user: overrides.user || process.env.USER || process.env.LOGNAME || "user",
    runSystemctl: overrides.runSystemctl || defaultRunSystemctl,
    hasSystemctl: overrides.hasSystemctl || defaultHasSystemctl,
    readLinger: overrides.readLinger || defaultReadLinger,
    log: overrides.log || (() => {}),
    isEnabled,
    isRunning,
    enable,
    disable,
    ...overrides,
  };
}

export function unitPath(deps) {
  return join(deps.unitDir, UNIT_NAME);
}

export function isEnabled(deps) {
  // Prefer on-disk unit: matches mac-agent "plist exists" semantics and works offline.
  if (existsSync(unitPath(deps))) return true;
  const res = deps.runSystemctl(["is-enabled", UNIT_NAME]);
  return res.status === 0 && String(res.stdout || "").trim() === "enabled";
}

export function isRunning(deps) {
  const res = deps.runSystemctl(["is-active", UNIT_NAME]);
  return res.status === 0 && String(res.stdout || "").trim() === "active";
}

function rollbackUnit(deps) {
  try {
    rmSync(unitPath(deps), { force: true });
  } catch {
    // best-effort
  }
}

export function enable(deps) {
  if ((deps.platform || platform()) !== "linux") {
    return { ok: false, enabled: false, error: "仅支持 Linux" };
  }
  if (!deps.hasSystemctl()) {
    return {
      ok: false,
      enabled: false,
      error:
        "未找到 systemctl。Linux 版需要 systemd user 服务常驻；也可前台运行：cxx start",
    };
  }

  // Whether a unit already existed (upgrade / re-enable) vs first install.
  // Used to decide how hard to roll back if restart fails after enable.
  const hadUnit = existsSync(unitPath(deps));

  const logPath = join(deps.homeDir, ".cxx", "remote", "daemon.log");
  mkdirSync(dirname(logPath), { recursive: true });
  mkdirSync(deps.unitDir, { recursive: true });

  const programArguments = daemonProgramArguments(deps.configPath);
  const unitBody = buildUnitFile({
    programArguments,
    logPath,
    pathEnv: systemdPath(deps.homeDir),
  });
  writeFileSync(unitPath(deps), unitBody);

  const reload = deps.runSystemctl(["daemon-reload"]);
  if (reload.status !== 0) {
    const msg = String(reload.stderr || reload.stdout || "systemctl daemon-reload 失败").trim();
    deps.log(`daemon-reload: ${msg}`);
    if (!hadUnit) rollbackUnit(deps);
    return { ok: false, enabled: hadUnit, error: msg };
  }

  // Install WantedBy link and start if inactive. `enable --now` alone does NOT
  // restart an already-active unit, so upgrades would keep the old process image.
  const en = deps.runSystemctl(["enable", "--now", UNIT_NAME]);
  if (en.status !== 0) {
    const msg = String(en.stderr || en.stdout || "systemctl enable --now 失败").trim();
    deps.log(`enable ${UNIT_NAME}: ${msg}`);
    deps.runSystemctl(["disable", "--now", UNIT_NAME]);
    if (!hadUnit) rollbackUnit(deps);
    deps.runSystemctl(["daemon-reload"]);
    return { ok: false, enabled: false, error: msg };
  }

  // Unconditional restart: picks up rewritten ExecStart/binary after daemon-reload
  // (parity with mac bootout+bootstrap / win task recreate+/Run).
  const rs = deps.runSystemctl(["restart", UNIT_NAME]);
  if (rs.status !== 0) {
    const msg = String(rs.stderr || rs.stdout || "systemctl restart 失败").trim();
    deps.log(`restart ${UNIT_NAME}: ${msg}`);
    if (!hadUnit) {
      deps.runSystemctl(["disable", "--now", UNIT_NAME]);
      rollbackUnit(deps);
      deps.runSystemctl(["daemon-reload"]);
      return { ok: false, enabled: false, error: msg };
    }
    // Upgrade path: leave the new unit on disk so the next manual restart can recover.
    return { ok: false, enabled: true, error: msg };
  }

  const result = { ok: true, enabled: true };
  const linger = deps.readLinger(deps.user);
  result.linger = linger;
  if (linger === false) {
    result.hint =
      `SSH 登出后 user 服务可能被停。建议执行: loginctl enable-linger ${deps.user}`;
    deps.log(result.hint);
  }
  return result;
}

export function disable(deps) {
  if (deps.hasSystemctl()) {
    deps.runSystemctl(["disable", "--now", UNIT_NAME]);
  }
  rmSync(unitPath(deps), { force: true });
  if (deps.hasSystemctl()) {
    deps.runSystemctl(["daemon-reload"]);
  }
  return { ok: true, enabled: false };
}
